export const routes = {
  home: '/',
  products: '/products',
  product: '/product/',
  contact: '/contact',
  singleProduct: '/product/:productId',
  cart: '/cart',
  checkout: '/checkout',
  upload: '/upload',
  signup: '/signup',
  login: '/login',
  authbeforecheckout: '/authbeforecheckout',
  ordersummary: '/ordersummary',
  terms: '/terms',
  account: '/account/:subPage',
  accountOrders: '/account/ordershistory/',
  accountOrder: '/account/ordershistory/:orderId',
  passwordChange: '/account/passwordchange',
  emailChange: '/account/emailchange',
  accountDetails: '/account/details',
  mobileSearch: '/search',
};
