export const routes = {
  home: '/',
  products: '/products',
  contact: '/contact',
  singleProduct: '/product/:productId',
  cart: '/cart',
  checkout: '/checkout',
  upload: '/upload',
  signup: '/signup',
  login: '/login',
  authbeforecheckout: '/authbeforecheckout',
  ordersummary: '/ordersummary',
  account: '/account/:subPage',
  accountOrders: '/account/ordershistory',
  accountOrder: '/account/ordershistory/:orderId',
  accountAddresses: '/account/addresses',
  accountDetails: '/account/details',
};
